package com.example.main;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Calendar;

public class server {
	
	public String[] names = new String[365];
	ServerSocket myServerSocket;
	Socket mySocket;
	int myPort = 8107;
	Calendar myCalendar;
	
	
	
	public server() throws IOException{
		
		fillNames();
		
		myServerSocket = new ServerSocket(myPort);

		while(true){
		connected();
		}
		

	}

	
	
	public void connected() throws IOException{
		mySocket = myServerSocket.accept();
		
		PrintWriter output = new PrintWriter(mySocket.getOutputStream(), true);
		myCalendar = Calendar.getInstance();
		int day = myCalendar.get(Calendar.DAY_OF_YEAR);
		output.println(names[day]);
		mySocket.close();
		
		
	}
	
	
	
	
	
	
	
	public void fillNames(){
		names[0]="Ingen namnsdag";
		names[1]="Svea";
		names[2]="Alfred, Alfrida";
		names[3]="Rut";
		names[4]="Hanna, Hannele";
		names[5]="Kasper, Melker, Baltsar";
		names[6]="August, Augusta";
		names[7]="Erland";
		names[8]="Gunnar, Gunder";
		names[9]="Sigurd, Sigbritt";
		names[10]="Jan, Jannike";
		names[11]="Frideborg, Fridolf";
		names[12]="Knut";
		names[13]="Felix, Felicia";
		names[14]="Laura, Lorentz";
		names[15]="Hjalmar, Helmer";
		names[16]="Anton, Tony";
		names[17]="Hilda, Hildur";
		names[18]="Henrik";
		names[19]="Fabian, Sebastian";
		names[20]="Agnes, Agneta";
		names[21]="Vincent, Viktor";
		names[22]="Frej, Freja";
		names[23]="Erika";
		names[24]="Paul, Pål";
		names[25]="Bodil, Boel";
		names[26]="Göte, Göta";
		names[27]="Karl, Karla";
		names[28]="Diana";
		names[29]="Gunilla, Gunhild";
		names[30]="Ivar, Joar";
		names[31]="Max, Maximilian";
		names[32]="Ingen namnsdag";
		names[33]="Disa, Hjördis";
		names[34]="Ansgar, Anselm";
		names[35]="Agata, Agda";
		names[36]="Dorotea, Doris";
		names[37]="Rikard, Dick";
		names[38]="Berta, Bert";
		names[39]="Fanny, Franciska";
		names[40]="Iris";
		names[41]="Yngve, Inge";
		names[42]="Evelina, Evy";
		names[43]="Agne, Ove";
		names[44]="Valentin";
		names[45]="Sigfrid";
		names[46]="Julia, Julius";
		names[47]="Alexandra, Sandra";
		names[48]="Frida, Fritiof";
		names[49]="Gabriella, Ella";
		names[50]="Vivianne";
		names[51]="Hilding";
		names[52]="Pia";
		names[53]="Torsten, Torun";
		names[54]="Mattias, Mats";
		names[55]="Sigvard, Sivert";
		names[56]="Torgny, Torkel";
		names[57]="Lage";
		names[58]="Maria";
		names[59]="Albin, Elvira";
		names[60]="Ernst, Erna";
		names[61]="Gunborg, Gunvor";
		names[62]="Adrian, Adriana";
		names[63]="Tora, Tove";
		names[64]="Ebba, Ebbe";
		names[65]="Camilla";
		names[66]="Siv";
		names[67]="Torbjörn, Torleif";
		names[68]="Edla, Ada";
		names[69]="Edvin, Egon";
		names[70]="Viktoria";
		names[71]="Greger";
		names[72]="Matilda, Maud";
		names[73]="Kristoffer, Christel";
		names[74]="Herbert, Gilbert";
		names[75]="Gertrud";
		names[76]="Edvard, Edmund";
		names[77]="Josef, Josefina";
		names[78]="Joakim, Kim";
		names[79]="Bengt";
		names[80]="Kennet, Kent";
		names[81]="Gerda, Gerd";
		names[82]="Gabriel, Rafael";
		names[83]="Ingen namnsdag";
		names[84]="Emanuel";
		names[85]="Rudolf, Ralf";
		names[86]="Malkolm, Morgan";
		names[87]="Jonas, Jens";
		names[88]="Holger, Holmfrid";
		names[89]="Ester";
		names[90]="Harald, Hervor";
		names[91]="Gudmund, Ingemund";
		names[92]="Ferdinand, Nanna";
		names[93]="Marianne, Marlene";
		names[94]="Irene, Irja";
		names[95]="Vilhelm, William";
		names[96]="Irma, Irmelin";
		names[97]="Nadja, Tanja";
		names[98]="Otto, Ottilia";
		names[99]="Ingvar, Ingvor";
		names[100]="Ulf, Ylva";
		names[101]="Liv";
		names[102]="Artur, Douglas";
		names[103]="Tiburtius";
		names[104]="Olivia, Oliver";
		names[105]="Patrik, Patricia";
		names[106]="Elias, Elis";
		names[107]="Valdemar, Volmar";
		names[108]="Olaus, Ola";
		names[109]="Amalia, Amelie, Emelie";
		names[110]="Anneli, Annika";
		names[111]="Allan, Glenn";
		names[112]="Georg, Göran";
		names[113]="Vega";
		names[114]="Markus";
		names[115]="Teresia, Terese";
		names[116]="Engelbrekt";
		names[117]="Ture, Tyra";
		names[118]="Tyko";
		names[119]="Mariana, (Valborgsmässoafton)";
		names[120]="Valborg, (Första maj)";
		names[121]="Filip, Filippa";
		names[122]="John, Jane";
		names[123]="Monika, Mona";
		names[124]="Gotthard, Erhard";
		names[125]="Marit, Rita";
		names[126]="Carina, Carita";
		names[127]="Åke";
		names[128]="Reidar, Reidun";
		names[129]="Esbjörn, Styrbjörn";
		names[130]="Märta, Märit";
		names[131]="Charlotta, Lotta";
		names[132]="Linnea, Linn";
		names[133]="Halvard, Halvar";
		names[134]="Sofia, Sonja";
		names[135]="Ronald, Ronny";
		names[136]="Rebecka, Ruben";
		names[137]="Erik";
		names[138]="Maj, Majken";
		names[139]="Karolina, Carola";
		names[140]="Konstantin, Conny";
		names[141]="Hemming, Henning";
		names[142]="Desideria, Desirée";
		names[143]="Ivan, Vanja";
		names[144]="Urban";
		names[145]="Vilhelmina, Vilma";
		names[146]="Beda, Blenda";
		names[147]="Ingeborg, Borghild";
		names[148]="Yvonne, Jeanette";
		names[149]="Vera, Veronika";
		names[150]="Petronella, Pernilla";
		names[151]="Gun, Gunnel";
		names[152]="Rutger, Roger";
		names[153]="Ingemar, Gudmar";
		names[154]="Solbritt, Solveig";
		names[155]="Bo";
		names[156]="Gustav, Gösta";
		names[157]="Robert, Robin";
		names[158]="Eivor, Majvor";
		names[159]="Börje, Birger";
		names[160]="Svante, Boris";
		names[161]="Bertil, Berthold";
		names[162]="Eskil";
		names[163]="Aina, Aino";
		names[164]="Håkan, Hakon";
		names[165]="Margit, Margot";
		names[166]="Axel, Axelina";
		names[167]="Torborg, Torvald";
		names[168]="Björn, Bjarne";
		names[169]="Germund, Görel";
		names[170]="Linda";
		names[171]="Alf, Alvar";
		names[172]="Paulina, Paula";
		names[173]="Adolf, Alice";
		names[174]="Ingen namnsdag";
		names[175]="David, Salomon";
		names[176]="Rakel, Lea";
		names[177]="Selma, Fingal";
		names[178]="Leo";
		names[179]="Peter, Petra";
		names[180]="Elof, Leif";
		names[181]="Aron, Mirjam";
		names[182]="Rosa, Rosita";
		names[183]="Aurora";
		names[184]="Ulrika, Ulla";
		names[185]="Laila, Ritva";
		names[186]="Esaias, Jessika";
		names[187]="Klas";
		names[188]="Kjell";
		names[189]="Jörgen, Örjan";
		names[190]="André, Andrea";
		names[191]="Eleonora, Ellinor";
		names[192]="Herman, Hermine";
		names[193]="Joel, Judit";
		names[194]="Folke";
		names[195]="Ragnhild, Ragnvald";
		names[196]="Reinhold, Reine";
		names[197]="Bruno";
		names[198]="Fredrik, Fritz";
		names[199]="Sara";
		names[200]="Margareta, Greta";
		names[201]="Johanna";
		names[202]="Magdalena, Madeleine";
		names[203]="Emma";
		names[204]="Kristina, Kerstin";
		names[205]="Jakob";
		names[206]="Jesper";
		names[207]="Marta";
		names[208]="Botvid, Seved";
		names[209]="Olof";
		names[210]="Algot";
		names[211]="Helena, Elin";
		names[212]="Per";
		names[213]="Karin, Kajsa";
		names[214]="Tage";
		names[215]="Arne, Arnold";
		names[216]="Ulrik, Alrik";
		names[217]="Alfons, Inez";
		names[218]="Dennis, Denise";
		names[219]="Silvia, Sylvia";
		names[220]="Roland";
		names[221]="Lars";
		names[222]="Susanna";
		names[223]="Klara";
		names[224]="Kaj";
		names[225]="Uno";
		names[226]="Stella, Estelle";
		names[227]="Brynolf";
		names[228]="Verner, Valter";
		names[229]="Ellen, Lena";
		names[230]="Magnus, Måns";
		names[231]="Bernhard, Bernt";
		names[232]="Jon, Jonna";
		names[233]="Henrietta, Henrika";
		names[234]="Signe, Signhild";
		names[235]="Bartolomeus";
		names[236]="Lovisa, Louise";
		names[237]="Östen";
		names[238]="Rolf, Raoul";
		names[239]="Fatima, Leila";
		names[240]="Hans, Hampus";
		names[241]="Albert, Albertina";
		names[242]="Arvid, Vidar";
		names[243]="Sam, Samuel";
		names[244]="Justus, Justina";
		names[245]="Alfhild, Alva";
		names[246]="Gisela";
		names[247]="Adela, Heidi";
		names[248]="Lilian, Lilly";
		names[249]="Kevin, Roy";
		names[250]="Alma, Hulda";
		names[251]="Anita, Annette";
		names[252]="Tord, Turid";
		names[253]="Dagny, Helny";
		names[254]="Åsa, Åslög";
		names[255]="Sture";
		names[256]="Ida";
		names[257]="Sigrid, Siri";
		names[258]="Dag, Daga";
		names[259]="Hildegard, Magnhild";
		names[260]="Orvar";
		names[261]="Fredrika";
		names[262]="Elise, Lisa";
		names[263]="Matteus";
		names[264]="Maurits, Moritz";
		names[265]="Tekla, Tea";
		names[266]="Gerhard, Gert";
		names[267]="Tryggve";
		names[268]="Enar, Einar";
		names[269]="Dagmar, Rigmor";
		names[270]="Lennart, Leonard";
		names[271]="Mikael, Mikaela";
		names[272]="Helge";
		names[273]="Ragnar, Ragna";
		names[274]="Ludvig, Love";
		names[275]="Evald, Osvald";
		names[276]="Frans, Frank";
		names[277]="Bror";
		names[278]="Jenny, Jennifer";
		names[279]="Birgitta, Britta";
		names[280]="Nils";
		names[281]="Ingrid, Inger";
		names[282]="Harry, Harriet";
		names[283]="Erling, Jarl";
		names[284]="Valfrid, Manfred";
		names[285]="Berit, Birgit";
		names[286]="Stellan";
		names[287]="Hedvig, Hillevi";
		names[288]="Finn";
		names[289]="Antonia, Toini";
		names[290]="Lukas";
		names[291]="Tore, Tor";
		names[292]="Sibylla";
		names[293]="Ursula, Yrsa";
		names[294]="Marika, Marita";
		names[295]="Severin, Sören";
		names[296]="Evert, Eilert";
		names[297]="Inga, Ingalill";
		names[298]="Amanda, Rasmus";
		names[299]="Sabina";
		names[300]="Simon, Simone";
		names[301]="Viola";
		names[302]="Elsa, Isabella";
		names[303]="Edit, Edgar";
		names[304]="Ingen namnsdag";
		names[305]="Tobias";
		names[306]="Hubert, Hugo";
		names[307]="Sverker";
		names[308]="Eugen, Eugenia";
		names[309]="Gustav Adolf";
		names[310]="Ingegerd, Ingela";
		names[311]="Vendela";
		names[312]="Teodor, Teodora";
		names[313]="Martin, Martina";
		names[314]="Mårten";
		names[315]="Konrad, Kurt";
		names[316]="Kristian, Krister";
		names[317]="Emil, Emilia";
		names[318]="Leopold";
		names[319]="Vibeke, Viveka";
		names[320]="Naemi, Naima";
		names[321]="Lillemor, Moa";
		names[322]="Elisabet, Lisbet";
		names[323]="Pontus, Marina";
		names[324]="Helga, Olga";
		names[325]="Cecilia, Sissela";
		names[326]="Klemens";
		names[327]="Gudrun, Rune";
		names[328]="Katarina, Katja";
		names[329]="Linus";
		names[330]="Astrid, Asta";
		names[331]="Malte";
		names[332]="Sune";
		names[333]="Andreas, Anders";
		names[334]="Oskar, Ossian";
		names[335]="Beata, Beatrice";
		names[336]="Lydia";
		names[337]="Barbara, Barbro";
		names[338]="Sven";
		names[339]="Nikolaus, Niklas";
		names[340]="Angela, Angelika";
		names[341]="Virginia";
		names[342]="Anna";
		names[343]="Malin, Malena";
		names[344]="Daniel, Daniela";
		names[345]="Alexander, Alexis";
		names[346]="Lucia";
		names[347]="Sten, Sixten";
		names[348]="Gottfrid";
		names[349]="Assar";
		names[350]="Stig";
		names[351]="Abraham";
		names[352]="Isak";
		names[353]="Israel, Moses";
		names[354]="Tomas";
		names[355]="Natanael, Jonatan";
		names[356]="Adam";
		names[357]="Eva, (Julafton)";
		names[358]="Ingen namnsdag";
		names[359]="Stefan, Staffan, (Annandag jul)";
		names[360]="Johannes, Johan";
		names[361]="Benjamin, (Värnlösa barns dag)";
		names[362]="Natalia, Natalie";
		names[363]="Abel, Set";
		names[364]="Sylvester";
	}
	
}
